[build]
  base = "LibraryAngular/library-shop"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "src/app/dist/library-shop"

[context.production.environment]
  NODE_ENV = "production"