[build]
  base = "LibraryAngular/library-shop"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "library-shop/dist"

[context.production.environment]
  NODE_ENV = "production"