[build]
  base = "LibraryAngular/library-shop/src/app"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/library-shop"

[context.production.environment]
  NODE_ENV = "production"